// // Codes generated by Tutorial

// //import React from 'react';

// function convertCurrency(amount: number, currency: string): string {
//   return `${amount} ${currency}` ;
// }
// const argument = <p>{convertCurrency(100, 'USD')}</p>

// export default function Button() {
//   return (
//     <button className='bg-blue-500 text-white px-4 py-2 rounded'>
//       Click Me and {argument}
//     </button>
//   );
// }


// usage of typingScript in React especially props 

export default function Button({
  backgroundColor,
  fontSize}: {
    backgroundColor: string
    fontSize: number
  }) {
  return(
    <button className="bg-blue-500 text-white px-4 py-2 rounded ">
      Click Me
    </button>
  );
}