// // Codes generated by Tutorial

// //import React from 'react';

// function convertCurrency(amount: number, currency: string): string {
//   return `${amount} ${currency}` ;
// }
// const argument = <p>{convertCurrency(100, 'USD')}</p>

// export default function Button() {
//   return (
//     <button className='bg-blue-500 text-white px-4 py-2 rounded'>
//       Click Me and {argument}
//     </button>
//   );
// }


// usage of typingScript in React especially props 
// on this part if you don't know the type of props but declared at the top you can press Ctrl + Space to see the type of props
type color = 'red' | 'green' | 'blue' | 'yellow' | 'purple'
type ButtonProps = {
  backgroundColor: color;
  textColor: color
  fontSize: number;
}
export default function Button({
  backgroundColor,
  textColor,
  fontSize}: ButtonProps) {
  return(
    <button className="bg-blue-500 text-white px-4 py-2 rounded "
      style={{
        backgroundColor: backgroundColor,
        fontSize: fontSize, 
        color:textColor,
      }}>
      Click Me
    </button>
  );
}